name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  kubesec_input_file:
    description: 'Input file to kubesec'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
