name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      kubesec:
        # Docker Hub image
        image: kubesec/kubesec:512c5e0
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "wget --quiet --tries=1 --spider http://localhost:8080/healtz || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 8080:8080
    steps:
    - uses: actions/checkout@v1
    - run: |
        npm install
        npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      kubesec:
        # Docker Hub image
        image: kubesec/kubesec:512c5e0
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "wget --quiet --tries=1 --spider http://localhost:8080/healtz || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 8080:8080
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        kubesec_input_file: '__tests__/test.yaml'
        kubesec_url: 'http://localhost:8080/scan'